### ISSUE TITLE
Amazing and simple code base! Just a quick thing, did you try fine-tuning with QLORA?

### ISSUE THREAD

**Issue by shamanez** [gersteinlab/Struc-Bench#1]
I went through the fine-tuning code and noticed that you had loaded the model in 8-bits. I just wonder whether you have tried Qlora.  

if so, how did it go>?

**Comment by RyanZong2233** [comment]
We refer to the fine-tuning method of alpaca-lora. You can refer to https://github.com/tloen/alpaca-lora

**Comment by tangxiangru** [comment]
Qlora has not been included. Hope to see the contribution from the community.
